# Generated by Django 3.1.7 on 2021-03-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': '网站用户管理', 'verbose_name_plural': '网站用户管理'},
        ),
        migrations.AddField(
            model_name='siteuser',
            name='has_confirmed',
            field=models.BooleanField(default=False, verbose_name='是否邮箱验证'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后一次登录时间'),
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='确认码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.siteuser')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-create_time'],
            },
        ),
    ]
